# Generated by Django 2.0.7 on 2018-07-29 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='apply',
            name='doc_1',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='doc_2',
        ),
        migrations.AddField(
            model_name='doc',
            name='apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.Apply'),
        ),
    ]
